# Site settings
title: GSequencer
email: weedlight@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GSequencer is music composition tool using GObject and Gtk+.
  It features a source/drain and effect tree. As well a fully feautured
  notation editor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gsequencer.org" # the base hostname & protocol for your site
twitter_username: gsequencer
github_username:  weedlight

# Build settings
markdown: kramdown
